import { writeFile as _writeFile, mkdir } from 'node:fs/promises'
import { dirname } from 'node:path'
import { throttle } from '@antfu/utils'

async function writeFile(filePath: string, content: string) {
  await mkdir(dirname(filePath), { recursive: true })
  return await _writeFile(filePath, content, 'utf-8')
}

export const writeDeclaration = throttle(500,
  async (filepath: string, componentPaths: Map<string, string>) => {
    const code = `/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-async-component-loader

${Array.from(componentPaths)
  .map(
    ([p1, p2]) => `declare module '*/${p1}' {
  import AsyncComponent from '${p2}';
  export default AsyncComponent;
}`,
  )
  .join('\n')}
`

    await writeFile(filepath, code)
  },
)
